# Site settings
title: 黄欢的博客
email: sadwxqezc@163.com
description: 美团金融后台研发工程师
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
baseurl: "/HuangHuanBlog"
url: "http://sadwxqezc.github.io/HuangHuanBlog/" # the base hostname & protocol for your site
github_username:  sadwxqezc

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"

# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
highlighter: rouge
# highlighter: false
